variables:
  VPS_HOST: "brunohendias.com.br"
  IDENTITY_PROJECT: "*$CI_PROJECT_NAME CI_COMMIT_REF_NAME*"

stages:
  - build
  - deploy

cache:
  untracked: true
  paths:
    - ./app/node_modules/
    - ./app/vendor/

Build:
  image: registry.gitlab.com/gerence/gerence
  stage: build
  script:
    - cd ./app
    - echo "Configuring composer"
    - wget https://getcomposer.org/installer
    - php installer
    - echo "Running composer install"
    - php composer.phar install --no-progress --ignore-platform-reqs
    - cp .env.prod .env
    - echo "Running NPM"
    - npm install --no-progress
    - npm run prod --no-progress
  artifacts:
    paths:
      - ./app/public/css
      - ./app/public/js
      - ./app/public/mix-manifest.json
    expire_in: 1 days
    when: always


#Deploy:
  #stage: deploy
  #dependencies:
    #- Build
  #script:
    #- echo "Running Deploy"
    #- mkdir -p ~/.ssh
    #- chmod 700 ~/.ssh