version: '3'
services:

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbgerence
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: gerence
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql:/docker-entrypoint-initdb.d

# Volumes
volumes:
  dbdata:
    driver: local