variables:
  VPS_HOST: "brunohendias.com.br"
  IDENTITY_PROJECT: "*$CI_PROJECT_NAME CI_COMMIT_REF_NAME*"

stages:
  - prepare
  - test
  - analysis
  - build
  - deploy

cache:
  untracked: true
  paths:
    - app/node_modules/
    - app/vendor/

prepare_project:
  stage: prepare
  script:
    - echo "Configuring composer"
    - wget https://getcomposer.org/installer
    - php installer
    - echo "Running composer install"
    - php composer.phar install --no-dev --optimize-autolader --no-progress
    - cp .env.prod .env

Tests:
  stage: test
  dependencies:
    - prepare_project
  script:
    - echo "Runnit PHPUnit"
    - ./vendor/bin/phpunit

Static_Analysis:
  stage: analysis
  dependencies:
    - prepare_project
  script:
    - echo "Running Psalm"
    - ./vendor/bin/psalm --show-info=true

Build:
  stage: build
  dependencies:
    - prepare_project
  script:
    - echo "Running NPM"
    - npm install --no-progress
    - npm run prod --no-progress
  artifacts:
    paths:
      - public/css
      - public/js
      - public/mix-manifest.json
    expire_in: 1 days
    when: always


#Deploy:
  #stage: deploy
  #dependencies:
    #- Build
  #script:
    #- echo "Running Deploy"
    #- mkdir -p ~/.ssh
    #- chmod 700 ~/.ssh
